### ISSUE TITLE
generator-mayhem branch incorrect reference. 

### ISSUE THREAD

**Issue by thejones** [SitePen/mayhem#22]
When running bower install after using the generator I receive the following error. 
fatal: reference is not a tree: c20d2880d0a4ee506220db4ccaa5dbc31779ab29

https://github.com/SitePen/mayhem/blob/generator-mayhem/app/templates/_bower.json#l13

Unsure if this should point to the latest commit - 3f44857499180e60ded3cf8d07226de7a7cfdce7 or simply git@github.com:SitePen/mayhem.git

**Comment by csnover** [comment]
The generator is out of date and I’m sure not functioning right now, so it’s probably not necessary to submit more than one ticket against it unless you are looking for guidance on how to fix it :)

**Comment by thejones** [comment]
I understand it is out of date but the guides still reference it heavily for creating your first app. Unless there is another generator!? 

"The Mayhem generator described in this section is not yet in the master branch. An out of date work in progress is available in the generator-mayhem branch. Getting this working with master would be a great way to get involved." 

I suppose that my goal here is to receive assistance in getting this branch up to date so that others could have some initial success. That being said, my selfish goal is simply to get a small sample app working. 

TypeScript will be new to a lot of people, myself included, and this is the only place I have seen reference to a sample application. If there is another project I can reference to work through these issues it would be magical. I am not sure if my issues at this point are with my dojo/config, TypeScript, other. I am using the stub application that the generator creates as my "base" for all of my testing.

**Comment by dylans** [comment]
@thejones the current state of things is that on master, we're doing a pretty major refactor of things. Once that is finished, our plan is to update the docs, the generator, and update the not yet published sample app. That said, at the same time we're trying to get Intern 3 out the door, as well as some progress on Dojo 2, so it's going to be at least a few weeks before we're back in full swing on Mayhem.

**Comment by thejones** [comment]
Thanks Dylan. I look forward to it.
